<?php $this->headTitle('Cadastro de Títulos | NR12 Sistema Inventariante'); ?>

<h1><?php echo $this->translate('Adicionar novo título'); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('titulo', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>

<a class="btn" href="<?php echo $this->url('titulo')?>">Voltar</a>