<?php $this->headTitle('Cadastro de Produtos | NR12 Sistema'); ?>
<h2>Lista de Produtos</h2>
	
<a class="btn btn-success" href="<?php echo $this->url('produto', array('action'=>'add')); ?>">Novo Produto</a>

<table class="table">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Categoria</th>
            <th width="130">Ações</th>
        </tr>
    </thead>
      
    <tbody>
        <?php foreach($produtos as $produto): ?>
            <tr>            
                <td><?php echo $this->escapeHtml($produto->getDescricao()) ?></td>
                <td><?php //echo utf8_encode($produto->getCategoria()->getDescricao()) ?></td>
                
                <td class="center">
                    <a class="btn btn-mini btn-warning" href="<?php echo $this->url('produto',
                        array('action'=>'edit', 'id' => $produto->getProdutoId()));?>">Editar</a>
                    
                    <a class="btn btn-mini btn-danger" href="<?php echo $this->url('produto',
                        array('action'=>'delete', 'id' => $produto->getProdutoId()));?>">Excluir
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>